// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/mailbadger/app/config"
	"github.com/mailbadger/app/sqs"
	"github.com/mailbadger/app/storage"
	"github.com/mailbadger/app/storage/redis"
)

// Injectors from app.go:

func initApp(ctx context.Context, conf config.Config) (app, error) {
	db := storage.New(conf)
	storageStorage := storage.From(db)
	redisStore, err := redis.NewStoreFrom(conf)
	if err != nil {
		return app{}, err
	}
	awsConfig, err := initAwsConfig(ctx)
	if err != nil {
		return app{}, err
	}
	client := sqs.NewClient(awsConfig)
	sendEmailQueueURL, err := sqs.GetSendEmailQueueURL(ctx, client)
	if err != nil {
		return app{}, err
	}
	mainHandler := newHandler(storageStorage, redisStore, sendEmailQueueURL)
	queueURL := newQueueURL(sendEmailQueueURL)
	consumer := sqs.NewConsumerFrom(conf, queueURL, client)
	mainApp := newApp(mainHandler, consumer)
	return mainApp, nil
}

// app.go:

type app struct {
	handler  *handler
	consumer sqs.Consumer
}

func newApp(h *handler, c sqs.Consumer) app {
	return app{
		handler:  h,
		consumer: c,
	}
}
